version: 2.1
jobs:
  lint:
    environment:
      _JAVA_OPTIONS: "-Xmx4g"
      GRADLE_OPTS: "-Dorg.gradle.workers.max=2"
    resource_class: small
    docker:
      - image: cimg/openjdk:17.0.9
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run lint checks
          command: gradle detekt -DREPO_USERNAME=$REPO_USERNAME -DTOKEN=$TOKEN -DREPO_PUBLISH_USERNAME=$REPO_PUBLISH_USERNAME -DREPO_PUBLISH_TOKEN=$REPO_PUBLISH_TOKEN
      - run:
          name: Run Unit Tests
          command: gradle che
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
workflows:
  version: 2
  build:
    jobs:
      - lint:
          context:
            - maven-repo
